### ISSUE TITLE
Procedure Hat blocks look like stack blocks when duplicated

### ISSUE THREAD

**Issue by csf30816** [GRA0007/Blue#11] opened 2016-07-28 22:40 UTC
I found a bug :)
![capture](https://cloud.githubusercontent.com/assets/18520232/17231909/5a16c91c-54ea-11e6-8aea-27cc280a146c.JPG)
Look at it!

**Comment by GRA0007** [comment] 2016-07-28 22:49
What's the bug here? Can you please explain what's going wrong?

**Comment by csf30816** [comment] 2016-07-29 15:39
Look at the Define block... It is a control block instead of a hat block, is that supposed to happen?

**Comment by GRA0007** [comment] 2016-07-29 23:39
Right you are, can you give instructions on how to replicate this bug?

**Comment by csf30816** [comment] 2016-08-04 16:43
Yes, sorry for being so late in response....
Create a block in stage and drag it into sprite

**Comment by NoMod-Programming** [comment] 2016-08-04 21:32
@csf30816 I've reproduced this bug, however it seems to be fixed in 1.2. @GRA0007 , have you update the website version to 1.3? Also, this only seems to affect the appearance. The custom blocks still work.

**Comment by csf30816** [comment] 2016-08-04 21:52
Yes that is what was cool! How they still work, but I thought I should report it any way

**Comment by GRA0007** [comment] 2016-08-05 01:45
Yeah sorry I'll update the website tonight :/

**Comment by csf30816** [comment] 2016-08-05 19:10
OK

**Comment by GRA0007** [comment] 2016-08-06 00:13
Ok it's updated now. Sorry for the delay.

**Comment by csf30816** [comment] 2016-08-09 20:37
Cool!

**Closed as completed** 2016-08-19 07:20 UTC
Labels: bug
